const configured=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');
const BASE=configured?(configured.endsWith('/api')?configured:`${configured}/api`):'/api';
export type ApiError={status:number;code:string;message:string;path?:string;details?:string[]};
type Envelope<T>={success:boolean;message?:string;data:T};
const token=()=>localStorage.getItem('sidms_token');
async function parseError(res:Response,path:string):Promise<never>{let body:any={};try{body=await res.json()}catch{};if(res.status===401){localStorage.removeItem('sidms_token');if(!location.pathname.startsWith('/login'))location.assign('/login')}throw{status:res.status,code:body.code||'REQUEST_FAILED',message:body.message||`Request failed (${res.status})`,path:body.path||path,details:body.details}as ApiError}
function unwrap<T>(body:any):T{return body&&typeof body==='object'&&'success'in body&&'data'in body?body.data as T:body as T}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);if(!(options.body instanceof FormData)&&options.body!==undefined)headers.set('Content-Type','application/json');headers.set('Accept','application/json');if(token())headers.set('Authorization',`Bearer ${token()}`);const res=await fetch(`${BASE}${path}`,{...options,headers});if(!res.ok)return parseError(res,path);if(res.status===204)return undefined as T;return unwrap<T>(await res.json())}
export async function requestBlob(path:string):Promise<{blob:Blob;filename?:string}>{const headers=new Headers();if(token())headers.set('Authorization',`Bearer ${token()}`);const res=await fetch(`${BASE}${path}`,{headers});if(!res.ok)return parseError(res,path);const d=res.headers.get('content-disposition')||'';const f=d.match(/filename\*?=(?:UTF-8'')?["']?([^"';]+)/i)?.[1];return{blob:await res.blob(),filename:f?decodeURIComponent(f):undefined}}
export function uploadWithProgress<T>(path:string,form:FormData,onProgress?:(percent:number)=>void):Promise<T>{return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',`${BASE}${path}`);x.setRequestHeader('Accept','application/json');if(token())x.setRequestHeader('Authorization',`Bearer ${token()}`);x.upload.onprogress=e=>e.lengthComputable&&onProgress?.(Math.round(e.loaded/e.total*100));x.onload=()=>{let b:any;try{b=x.responseText?JSON.parse(x.responseText):undefined}catch{b=x.responseText}if(x.status>=200&&x.status<300)resolve(unwrap<T>(b));else reject({status:x.status,code:b?.code||'UPLOAD_FAILED',message:b?.message||`Upload failed (${x.status})`,details:b?.details,path})};x.onerror=()=>reject({status:0,code:'NETWORK_ERROR',message:'Unable to reach the server',path});x.send(form)})}
export const api={get:<T>(p:string)=>request<T>(p),post:<T>(p:string,b?:unknown)=>request<T>(p,{method:'POST',body:b===undefined?undefined:b instanceof FormData?b:JSON.stringify(b)}),put:<T>(p:string,b?:unknown)=>request<T>(p,{method:'PUT',body:b===undefined?undefined:JSON.stringify(b)}),delete:<T>(p:string)=>request<T>(p,{method:'DELETE'})};
export function saveBlob({blob,filename}:{blob:Blob;filename?:string},fallback='download'){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename||fallback;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
